"""Static province and autonomous-community names (INE province codes)."""

from __future__ import annotations

PROVINCE_NAMES: dict[str, str] = {
    "01": "Araba/Álava",
    "02": "Albacete",
    "03": "Alicante/Alacant",
    "04": "Almería",
    "05": "Ávila",
    "06": "Badajoz",
    "07": "Illes Balears",
    "08": "Barcelona",
    "09": "Burgos",
    "10": "Cáceres",
    "11": "Cádiz",
    "12": "Castellón/Castelló",
    "13": "Ciudad Real",
    "14": "Córdoba",
    "15": "A Coruña",
    "16": "Cuenca",
    "17": "Girona",
    "18": "Granada",
    "19": "Guadalajara",
    "20": "Gipuzkoa",
    "21": "Huelva",
    "22": "Huesca",
    "23": "Jaén",
    "24": "León",
    "25": "Lleida",
    "26": "La Rioja",
    "27": "Lugo",
    "28": "Madrid",
    "29": "Málaga",
    "30": "Murcia",
    "31": "Navarra",
    "32": "Ourense",
    "33": "Asturias",
    "34": "Palencia",
    "35": "Las Palmas",
    "36": "Pontevedra",
    "37": "Salamanca",
    "38": "Santa Cruz de Tenerife",
    "39": "Cantabria",
    "40": "Segovia",
    "41": "Sevilla",
    "42": "Soria",
    "43": "Tarragona",
    "44": "Teruel",
    "45": "Toledo",
    "46": "Valencia/València",
    "47": "Valladolid",
    "48": "Bizkaia",
    "49": "Zamora",
    "50": "Zaragoza",
    "51": "Ceuta",
    "52": "Melilla",
}

# Province code -> autonomous community name (simplified NUTS-style grouping for UX)
PROVINCE_TO_COMMUNITY: dict[str, str] = {
    "01": "País Vasco",
    "02": "Castilla-La Mancha",
    "03": "Comunitat Valenciana",
    "04": "Andalucía",
    "05": "Castilla y León",
    "06": "Extremadura",
    "07": "Illes Balears",
    "08": "Cataluña",
    "09": "Castilla y León",
    "10": "Extremadura",
    "11": "Andalucía",
    "12": "Comunitat Valenciana",
    "13": "Castilla-La Mancha",
    "14": "Andalucía",
    "15": "Galicia",
    "16": "Castilla-La Mancha",
    "17": "Cataluña",
    "18": "Andalucía",
    "19": "Castilla-La Mancha",
    "20": "País Vasco",
    "21": "Andalucía",
    "22": "Aragón",
    "23": "Andalucía",
    "24": "Castilla y León",
    "25": "Cataluña",
    "26": "La Rioja",
    "27": "Galicia",
    "28": "Comunidad de Madrid",
    "29": "Andalucía",
    "30": "Región de Murcia",
    "31": "Comunidad Foral de Navarra",
    "32": "Galicia",
    "33": "Principado de Asturias",
    "34": "Castilla y León",
    "35": "Canarias",
    "36": "Galicia",
    "37": "Castilla y León",
    "38": "Canarias",
    "39": "Cantabria",
    "40": "Castilla y León",
    "41": "Andalucía",
    "42": "Castilla y León",
    "43": "Cataluña",
    "44": "Aragón",
    "45": "Castilla-La Mancha",
    "46": "Comunitat Valenciana",
    "47": "Castilla y León",
    "48": "País Vasco",
    "49": "Castilla y León",
    "50": "Aragón",
    "51": "Ceuta",
    "52": "Melilla",
}


def community_code_for_province(province_code: str) -> str:
    """Stable slug for autonomous community (until official INE CCAA codes are loaded)."""
    name = PROVINCE_TO_COMMUNITY.get(province_code)
    if not name:
        raise KeyError(province_code)
    return name.upper().replace(" ", "_").replace("-", "_").replace("Á", "A").replace("É", "E").replace("Í", "I").replace("Ó", "O").replace("Ú", "U").replace("Ñ", "N")
